# Netlify Configuration File

# This block defines the build settings for the site.
[build]
  # This setting tells Netlify where your serverless functions are located.
  functions = "netlify/functions"

# This block configures the runtime settings for your functions.
[functions]
  # This increases the timeout from the default 10 seconds to 26 seconds.
  timeout = 26
