# Netlify Configuration File

# This block defines the build settings for the site.
[build]
  # This setting tells Netlify where your serverless functions are located.
  functions = "netlify/functions"

# This block uses a wildcard to configure ALL functions.
# This is a more explicit way to set the timeout and avoids parsing errors.
[functions."*"]
  # Increase the timeout to 26 seconds.
  timeout = 26
